
jobs:
  - job: "UnitTests"
    displayName: "Tests_"
    strategy:
      matrix:
        base_extension_Node18:
          EXTENSION_DIRECTORY: 'azure-functions-nodejs-extensions-base'
          EXTENSION_NAME: 'Base'
          NODE_VERSION: '18.x'
        blob_extension_Node18:
          EXTENSION_DIRECTORY: 'azure-functions-nodejs-extensions-blob'
          EXTENSION_NAME: 'Blob'
          NODE_VERSION: '18.x'
        service_bus_extension_Node18:
          EXTENSION_DIRECTORY: 'azure-functions-nodejs-extensions-servicebus'
          EXTENSION_NAME: 'ServiceBus'
          NODE_VERSION: '18.x'        
        base_extension_Node20:
          EXTENSION_DIRECTORY: 'azure-functions-nodejs-extensions-base'
          EXTENSION_NAME: 'Base'
          NODE_VERSION: '20.x'
        blob_extension_Node20:
          EXTENSION_DIRECTORY: 'azure-functions-nodejs-extensions-blob'
          EXTENSION_NAME: 'Blob'
          NODE_VERSION: '20.x'
        service_bus_extension_Node20:
          EXTENSION_DIRECTORY: 'azure-functions-nodejs-extensions-servicebus'
          EXTENSION_NAME: 'ServiceBus'
          NODE_VERSION: '20.x'  
        base_extension_Node22:
          EXTENSION_DIRECTORY: 'azure-functions-nodejs-extensions-base'
          EXTENSION_NAME: 'Base'
          NODE_VERSION: '22.x'
        blob_extension_Node22:
          EXTENSION_DIRECTORY: 'azure-functions-nodejs-extensions-blob'
          EXTENSION_NAME: 'Blob'
          NODE_VERSION: '22.x'
        service_bus_extension_Node22:
          EXTENSION_DIRECTORY: 'azure-functions-nodejs-extensions-servicebus'
          EXTENSION_NAME: 'ServiceBus'
          NODE_VERSION: '22.x'  
        base_extension_Node24:
          EXTENSION_DIRECTORY: 'azure-functions-nodejs-extensions-base'
          EXTENSION_NAME: 'Base'
          NODE_VERSION: '24.x'
        blob_extension_Node24:
          EXTENSION_DIRECTORY: 'azure-functions-nodejs-extensions-blob'
          EXTENSION_NAME: 'Blob'
          NODE_VERSION: '24.x'
        service_bus_extension_Node24:
          EXTENSION_DIRECTORY: 'azure-functions-nodejs-extensions-servicebus'
          EXTENSION_NAME: 'ServiceBus'
          NODE_VERSION: '24.x'
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: $(NODE_VERSION)
      - bash: |
          cd $(EXTENSION_DIRECTORY)
        displayName: 'Install Node.js'
      - bash: |
          cd $(EXTENSION_DIRECTORY)
          npm ci
        displayName: 'npm ci'
      - bash: |
          cd $(EXTENSION_DIRECTORY)
          npm run build
        displayName: 'npm run build'
      - bash: |
          cd $(EXTENSION_DIRECTORY)
          npm run lint
        displayName: 'npm run lint'
      - bash: |
          cd $(EXTENSION_DIRECTORY)
          npm run updateVersion -- --validate
        displayName: 'validate version'
      - bash: |
          cd $(EXTENSION_DIRECTORY)
          npm test
        displayName: 'Run unit tests'
      - task: PublishTestResults@2
        displayName: 'Publish Unit Test Results'
        inputs:
            testResultsFiles: '$(EXTENSION_DIRECTORY)/test/unit-test-results.xml'
            testRunTitle: '$(Agent.JobName)'
        condition: succeededOrFailed()
