jobs:
  - job: "Build"
    displayName: 'Build Python Extensions'

    strategy:
      matrix:
        base_extension:
          EXTENSION_DIRECTORY: 'azure-functions-nodejs-extensions-base'
          EXTENSION_NAME: 'Base'
        blob_extension:
          EXTENSION_DIRECTORY: 'azure-functions-nodejs-extensions-blob'
          EXTENSION_NAME: 'Blob'
        service_bus_extension:
          EXTENSION_DIRECTORY: 'azure-functions-nodejs-extensions-servicebus'
          EXTENSION_NAME: 'ServiceBus'
    steps:
        - task: NodeTool@0
          inputs:
              versionSpec: 22.x
          displayName: 'Install Node.js'
        - bash: |
            cd $(EXTENSION_DIRECTORY)
            npm ci
        - bash: |
            cd $(EXTENSION_DIRECTORY)
            npm run updateVersion -- --buildNumber $(Build.BuildNumber)
          displayName: 'npm run updateVersion'
          condition: and(succeeded(), eq(${{ parameters.IsPrerelease }}, true))          
        - bash: | 
            cd $(EXTENSION_DIRECTORY)
            npm run build
            npm run minify
            npm prune --production
            npm pack
          displayName: 'npm run build'
    