parameters:
    - name: IsPrerelease
      type: boolean
      default: true

trigger:
  batch: true
  branches:
    include:
      - main
      - release/*

# CI only, does not trigger on PRs.
pr: none

schedules:
  - cron: '0 0 * * MON'
    displayName: At 12:00 AM, only on Monday
    branches:
      include:
        - main
    always: true

resources:
  repositories:
    - repository: 1es
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release
    - repository: eng
      type: git
      name: engineering
      ref: refs/tags/release

variables:
  - template: /ci/variables/build.yml@eng
  - template: /ci/variables/cfs.yml@eng

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1es
  parameters:
    pool:
      name: 1es-pool-azfunc
      image: 1es-windows-2022
      os: windows

    stages:
      - stage: Build
        jobs:
          - template: /eng/templates/jobs/build.yml@self
            parameters:
              IsPrerelease: ${{ parameters.IsPrerelease }}
      - stage: RunLinuxUnitTests
        dependsOn: []
        jobs:
          - template: /eng/templates/official/jobs/tests.yml@self
        pool:
          name: 1es-pool-azfunc
          image: 1es-ubuntu-22.04
          os: linux
      - stage: RunWindowsUnitTests
        dependsOn: []
        jobs:
          - template: /eng/templates/official/jobs/tests.yml@self