trigger:
  batch: true
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

schedules:
  - cron: '0 0 * * MON'
    displayName: At 12:00 AM, only on Monday
    branches:
      include:
        - main
    always: true

resources:
  repositories:
    - repository: 1es
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release

extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1es
  parameters:
    pool:
      name: 1es-pool-azfunc-public
      image: 1es-windows-2022
      os: windows
    sdl:
      codeql:
         compiled:
           enabled: true # still only runs for default branch
         runSourceLanguagesInSourceAnalysis: true
    settings:
      skipBuildTagsForGitHubPullRequests: ${{ variables['System.PullRequest.IsFork'] }}

    stages:
      - stage: Build
        jobs:
          - template: /eng/templates/jobs/minimal-build.yml@self
      - stage: RunUnitTests
        dependsOn: Build
        jobs:
          - template: /eng/templates/official/jobs/tests.yml@self
            parameters:
              PoolName: 1es-pool-azfunc-public